### ISSUE TITLE
Change Scale on solved workplanes?

### ISSUE THREAD

**Issue by zapador414** [GroundhogLighting/Groundhog#36]
Hi!
Is there any chance to modify the number range of the color scale on a solved workplane?
![untitled-1](https://user-images.githubusercontent.com/13966345/32370993-ddc3b00a-c06d-11e7-9e7e-678f5fffe049.jpg)

**Comment by germolinal** [comment]
Hello zapador414! 

Groundhog used to have that feature, but for some reason the process of changing the color of each solved workplane's pixel took a very long time. 

For getting more detailed information on your results you can always **right click on the solved workplane --> export to csv**

**Comment by germolinal** [comment]
I will retry this soon!

**Comment by germolinal** [comment]
Solved for version 1.0b. Working wonderfully!
