### ISSUE TITLE
Use gmsh for workplanes triangulation

### ISSUE THREAD

**Issue by agonzalezesteve** [GroundhogLighting/Groundhog#38]
I consider that the current _get_delaunay_triangles_ function from _Triangle.rb_ library draws really different triangle sizes (too big or too small)
<img src="https://user-images.githubusercontent.com/38532229/41590350-16d6722c-73b7-11e8-8f2b-f07052804545.png" width="400">
I prefer a smoother triangulation to have equally spaced sensors.

I saw on Twitter you are developing a new meshing algorithm.
<img src="https://user-images.githubusercontent.com/38532229/41591322-b0737dd8-73b9-11e8-9585-533c912c8f80.png" width="400">
I wanted to know how at what stage is the new tool.

**Comment by germolinal** [comment]
I am honestly developing it as fast as I can! but it is still slower than I would want... I believe I am close, but am not sure exactly when will I be able to ship it.

This is exactly the issue that made me start with the whole new development of Groundhog, so it WILL be present as soon as possible.

Thanks for asking and being interested!

Best!

**Comment by agonzalezesteve** [comment]
Ok perfect, so I close this issue.
